name: Test

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Native Build and Audio Tests (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: windows-x64
            os: windows-2022
            node_arch: x64
            archflags: ''
            audio_runtime: true
          - target: windows-arm64
            os: windows-11-vs2026-arm
            node_arch: arm64
            archflags: ''
            audio_runtime: false
          - target: linux-x64
            os: ubuntu-22.04
            node_arch: x64
            archflags: ''
            audio_runtime: true
          - target: linux-arm64
            os: ubuntu-22.04-arm
            node_arch: arm64
            archflags: ''
            audio_runtime: true
          - target: darwin-x64
            os: macos-26
            node_arch: x64
            archflags: '-arch x86_64'
            audio_runtime: true
          - target: darwin-arm64
            os: macos-26
            node_arch: arm64
            archflags: '-arch arm64'
            audio_runtime: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          architecture: ${{ matrix.node_arch }}
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Build Current Binary
        env:
          ARCHFLAGS: ${{ matrix.archflags }}
        run: npm run build:rebuild

      - name: Build TypeScript Distribution
        if: matrix.audio_runtime
        run: npm run build:ci

      - name: Audio Device - Unix
        if: matrix.audio_runtime && !startsWith(matrix.target, 'windows-')
        uses: LABSN/sound-ci-helpers@v1

      - name: Audio Device - Windows
        if: matrix.audio_runtime && startsWith(matrix.target, 'windows-')
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          C:\'Program Files'\7-Zip\7z.exe x C:\Scream3.6.zip -oC:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream

      - name: Run Unit Tests
        if: matrix.audio_runtime
        run: npm run test:ci
